'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    // Insert initial data into the "TaxMaster" table
    await queryInterface.bulkInsert('TaxMaster',[
      {
        id: 1,
        name: 'Goods and Services Tax (GST)',
        description: 'Tax applicable on the supply of goods and services in India.',
        start_date: '01-01-2023',
        end_date: '01-01-2024',
        status: true,
        percentage: 18,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        name: 'Value Added Tax (VAT)',
        description: 'A consumption tax levied on the value added to goods and services.',
        start_date: '01-01-2024',
        end_date: '01-01-2025',
        status: true,
        percentage: 18.5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        name: 'Corporate Tax',
        description: 'Tax imposed on the income or capital of corporations.',
        start_date: '01-01-2025',
        end_date: '01-01-2026',
        status: true,
        percentage: 18.75,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        name: 'Income Tax',
        description: 'Tax levied on individual earnings or household income.',
        start_date: '01-01-2026',
        end_date: '01-01-2027',
        status: true,
        percentage: 19,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        name: 'Sales Tax',
        description: 'Tax imposed on sales of goods and services, typically at the point of sale.',
        start_date: '01-01-2027',
        end_date: '01-01-2028',
        status: true,
        percentage: 19.5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        name: 'Excise Duty',
        description: 'Tax on the production, sale, or consumption of certain goods within a country.',
        start_date: '01-01-2028',
        end_date: '01-01-2029',
        status: true,
        percentage: 20,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        name: 'Property Tax',
        description: 'Tax levied on real estate properties.',
        start_date: '01-01-2029',
        end_date: '01-01-2030',
        status: true,
        percentage: 20.5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        name: 'Inheritance Tax',
        description: 'Tax imposed on an individual who inherits assets from a deceased person.',
        start_date: '01-01-2030',
        end_date: '01-01-2031',
        status: true,
        percentage: 21,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        name: 'Capital Gains Tax',
        description: 'Tax on the profit from the sale of assets like stocks, bonds, or real estate.',
        start_date: '01-01-2031',
        end_date: '01-01-2032',
        status: true,
        percentage: 21.5,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        name: 'Customs Duty',
        description: 'Tax imposed on imports and exports of goods.',
        start_date: '01-01-2032',
        end_date: '01-01-2033',
        status: true,
        percentage: 22,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    // Remove the inserted data if we need to revert the seeder
    await queryInterface.bulkDelete('TaxMaster', null, {});
  },
};
